### ISSUE TITLE
AlarmCallbacks are no longer compatible with v1.1(.1)

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#1221]
Users noticed that for example the Slack plugin is no longer working with v1.1(.1):

    java.lang.NoSuchMethodError: org.graylog2.plugin.alarms.AlertCondition.getSearchHits()Ljava/util/List;
	at org.graylog2.alarmcallbacks.slack.SlackClient.buildPostParametersFromAlertCondition(SlackClient.java:163)
	at org.graylog2.alarmcallbacks.slack.SlackClient.trigger(SlackClient.java:107)
	at org.graylog2.alarmcallbacks.slack.SlackAlarmCallback.call(SlackAlarmCallback.java:58)
	at org.graylog2.rest.resources.streams.alerts.StreamAlertReceiverResource.sendDummyAlert(StreamAlertReceiverResource.java:168)

Indeed that method was removed in bc83b850d16a69e237cbbb4456d2a6bc64d993b2. A commit the same day (516f5227bde6227a5a79696c092f358ee9fd22f4) tried to "sustain plugin api backwards compatibility" but did not add the method back to the interface.

#### We will need to upload new alarm callback plugins that use the 1.1.2 plugin-interfaces after fixing this.

**Comment by bassrock** [comment]
:+1:

**Comment by lennartkoopmann** [comment]
Adding note that we need to release new alarm callback plugins using the 1.1.2 plugin interfaces dependency after this.
