### ISSUE TITLE
Drools Rule File format

### ISSUE THREAD

**Issue by bla-ckbox** [Graylog2/graylog2-server#387]
with graylog2-server-0.20.0-rc.1 and java 1.7.0_45, graylog stop  when loading Drools Rule File with error:

```
2014-01-22 12:43:35,859 INFO : org.graylog2.indexer.Deflector - Found deflector alias <graylog2_deflector>. Using it.
2014-01-22 12:43:37,917 ERROR: org.graylog2.RulesEngineImpl - Unable to resolve ObjectType 'LogMessage' : [Rule name='host shortname']

2014-01-22 12:43:37,917 ERROR: org.graylog2.RulesEngineImpl - Error importing : 'org.graylog2.plugin.logmessage.LogMessage'
2014-01-22 12:43:37,918 ERROR: org.graylog2.RulesEngineImpl - Rule Compilation error : [Rule name='host shortname']
        defaultpkg/Rule_host_shortname_38858131e47c432a85133d064461872d.java (2:89) : Only a type can be imported. org.graylog2.plugin.logmessage.LogMessage resolves to a package
        defaultpkg/Rule_host_shortname_38858131e47c432a85133d064461872d.java (7:496) : m cannot be resolved
        defaultpkg/Rule_host_shortname_38858131e47c432a85133d064461872d.java (9:542) : m cannot be resolved
```

Drools Rule File:

```
import org.graylog2.plugin.logmessage.LogMessage
import java.util.regex.Matcher
import java.util.regex.Pattern

rule "host shortname"
  when
    m : LogMessage( host matches "^[A-Za-z0-9-]+\\.mydomaine\\.fr$" )
  then
    Matcher matcher = Pattern.compile("^([A-Za-z0-9-]+)").matcher(m.getHost());
    if (matcher.find()) {
      m.setHost( matcher.group(1).toLowerCase() );
    }
end

```

this file works well with graylog2-server-0.13.0
