### ISSUE TITLE
Your project Graylog2/graylog2-server is using buggy third-party libraries [WARNING]

### ISSUE THREAD

**Issue by FDU-SE-LAB** [Graylog2/graylog2-server#5454]
Hi, there!

We are a research team working on third-party library analysis. We have found that some widely-used third-party libraries in your project have major/critical bugs, which will degrade the quality of your project. We highly recommend you to update those libraries to new versions.

We have attached the buggy third-party libraries and corresponding jira issue links below for you to have more detailed information.

1. org.apache.logging.log4j log4j-core(pom.xml)
version: 2.11.0

Jira issues:
Log4j2 throws NoClassDefFoundError in Java 9
affectsVersions:2.10.0,2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2129?filter=allopenissues
Empty Automatic-Module-Name Header
affectsVersions:2.10.0,2.11.0,3.0.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2254?filter=allopenissues
gc-free mixed async loging loses parameter values after the first appender
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2301?filter=allopenissues
Log4j 2.10+not working with SLF4J 1.8 in OSGI environment
affectsVersions:2.10.0,2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2305?filter=allopenissues
AsyncQueueFullMessageUtil causes unparsable message output
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2318?filter=allopenissues
AbstractLogger NPE hides actual cause when getFormat returns null
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2320?filter=allopenissues
AsyncLogger without specifying a level always uses ERROR
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2321?filter=allopenissues
Errors thrown in formatting may stop background threads
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2333?filter=allopenissues
JsonLayout not working with AsyncLoggerContextSelector in 2.11.0
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2341?filter=allopenissues
Typo in log4j-api Activator
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2343?filter=allopenissues
PropertiesUtil.reload() might throw NullPointerException
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2355?filter=allopenissues
NameAbbreviator skips first fragments
affectsVersions:2.11.0,2.11.1
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2365?filter=allopenissues
Outputs wrong message when used within overridden Throwable method
affectsVersions:2.8.1,2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2368?filter=allopenissues
StringBuilder escapeJson performs unnecessary Memory Allocations
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2373?filter=allopenissues
fix the CacheEntry map in ThrowableProxy#toExtendedStackTrace to be put and gotten with same key
affectsVersions:2.6.2,2.7,2.8,2.8.1,2.8.2,2.9.0,2.9.1,2.10.0,2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2389?filter=allopenissues
Fix incorrect links in Log4j web documentation.
affectsVersions:2.11.0
https://issues.apache.org/jira/projects/LOG4J2/issues/LOG4J2-2390?filter=allopenissues

2. commons-io commons-io(pom.xml,graylog-project-parent/pom.xml)
version: 2.6

Jira issues:
.gitattributes not correctly applied
affectsVersions:2.6
https://issues.apache.org/jira/projects/IO/issues/IO-516?filter=allopenissues
FilenameUtils.normalize should verify hostname syntax in UNC path
affectsVersions:2.6
https://issues.apache.org/jira/projects/IO/issues/IO-559?filter=allopenissues
Missing Javadoc in FilenameUtils causing Travis-CI build to fail
affectsVersions:2.6
https://issues.apache.org/jira/projects/IO/issues/IO-570?filter=allopenissues

3. commons-codec commons-codec(pom.xml, graylog-project-parent/pom.xml,graylog2-server/pom.xml)
version: 1.11

Jira issues:
InputStream not closed
affectsVersions:1.10;1.11
https://issues.apache.org/jira/projects/CODEC/issues/CODEC-225?filter=allopenissues

Sincerely~
FDU Software Engineering Lab
Jan 7th,2019

**Comment by jalogisch** [comment]
thank you for your contribution, can you please clarify which Graylog Version you have used for the test?
