### PR TITLE
Address severe issues with AlarmCallbacks

### LINKED ISSUE #1221: AlarmCallbacks are no longer compatible with v1.1(.1)
Users noticed that for example the Slack plugin is no longer working with v1.1(.1):

    java.lang.NoSuchMethodError: org.graylog2.plugin.alarms.AlertCondition.getSearchHits()Ljava/util/List;
	at org.graylog2.alarmcallbacks.slack.SlackClient.buildPostParametersFromAlertCondition(SlackClient.java:163)
	at org.graylog2.alarmcallbacks.slack.SlackClient.trigger(SlackClient.java:107)
	at org.graylog2.alarmcallbacks.slack.SlackAlarmCallback.call(SlackAlarmCallback.java:58)
	at org.graylog2.rest.resources.streams.alerts.StreamAlertReceiverResource.sendDummyAlert(StreamAlertReceiverResource.java:168)

Indeed that method was removed in bc83b850d16a69e237cbbb4456d2a6bc64d993b2. A commit the same day (516f5227bde6227a5a79696c092f358ee9fd22f4) tried to "sustain plugin api backwards compatibility" but did not add the method back to the interface.

#### We will need to upload new alarm callback plugins that use the 1.1.2 plugin-interfaces after fixing this.

### PR DESCRIPTION
**Pull request by lennartkoopmann**
This PR fixes #1221 and #1222. Please review and merge.

I thoroughly tested with all alert condition types triggering the Slack alarm callback plugin and the PagerDuty alarm callback plugin.

### CODE REVIEW

**Comment by lennartkoopmann** [comment]
wrong branch
