### PR TITLE
Degrade gracefully when OSHI/JNA native load fails on noexec data dir

### LINKED ISSUE #26471: 7.1 regression: server fails to start on noexec data dir (oshi/JNA UnsatisfiedLinkError)
## Summary

On 7.1, the server **fails to start** on hosts where the Graylog data directory (`<data_dir>`, e.g.  `/var/lib/graylog-server`) lives on a `noexec`-mounted filesystem. Startup aborts during Guice injector  creation with:

  ```
  NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystemJNA
  ...
  Caused by: UnsatisfiedLinkError: /var/lib/graylog-server/libnative/jna/jnaXXXX.tmp: failed to map
  segment from shared object
  ```

This is a regression introduced in **7.1.0** — the same host configuration starts fine on 7.0.

## Root cause

`NodeMetricPeriodical` (new in 7.1.0, #24493) eagerly creates a `CpuLoadGauge` in a **field  initializer**:

  ```java
  // NodeMetricPeriodical.java
  private final CpuLoadGauge cpuLoadGauge = new CpuLoadGauge();
  ```

  `CpuLoadGauge` in turn touches OSHI native code in **its own field initializer**:

  ```java
  // CpuLoadGauge.java
  private long[] lastTicks = processor().getSystemCpuLoadTicks();   // -> new
  SystemInfo().getHardware().getProcessor()
  ```

Because `NodeMetricPeriodical` is a `@Singleton` `Periodical` (eagerly instantiated when Guice builds the injector), this forces OSHI to load its native library **at startup**. OSHI/JNA unpacks the native `.so` into `<data_dir>/libnative/jna` (we deliberately moved `jna.tmpdir` there in #21223) and `dlopen()`s it. On a `noexec` mount the kernel refuses to map the executable segments -> `UnsatisfiedLinkError` -> injector creation fails -> the JVM never starts.

7.0 had no boot-time consumer that forced the OSHI native load, so the same `noexec` data dir was tolerated. 7.1 turns a latent, harmless misconfiguration into a hard boot failure.

`noexec` on `/var`, `/var/lib`, `/tmp`, etc. is common on CIS-benchmarked / STIG-hardened systems, so this is likely to hit security-conscious customers specifically.

## Impact

- Server will not start at all (not a degraded-metrics situation — total boot failure).
- Affects hardened/`noexec` deployments upgrading 7.0 -> 7.1.

## Workaround

Point the native lib dir at an `exec`-capable location via JVM options:

  ```
  -Djna.tmpdir=/opt/graylog/libnative/jna -Dio.netty.native.workdir=/opt/graylog/libnative
  ```

(directory must be writable by the graylog user and on a non-`noexec` mount).

## Proposed fix

Node metrics are a nice-to-have; their unavailability must not prevent startup.
1. Make OSHI/`CpuLoadGauge` initialization **lazy and guarded** — wrap the native access in try/catch, log a single warning, and disable the CPU-load metric (return `null`/`NaN`) instead of propagating the error.
  2. Remove the eager field initializers (`new CpuLoadGauge()` in `NodeMetricPeriodical`, and `lastTicks =  processor()...` in `CpuLoadGauge`) so nothing forces the native load during injector creation; defer to first periodical run.
  3. Consider applying the same defensive guard to `OshiService` so any OSHI-backed startup path degrades  gracefully on `noexec`/restricted hosts.

## Affected versions

7.1.0 and later. Not present in 7.0.x.

## References

- Introduced by #24493 (Cluster Nodes UI improvements)
- Related: #21223 (jna.tmpdir relocation to data dir)

### PR DESCRIPTION
**Pull request by patrickmann**
Closes #26471

## Description

On 7.1+, the server fails to start on hosts where the Graylog data directory is on a `noexec`-mounted filesystem (common on hardened systems). Startup dies while the periodicals are being constructed with `NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystemJNA` /  `UnsatisfiedLinkError: ... failed to map segment from shared object`.

The regression is due to `NodeMetricPeriodical` (new in 7.1.0), that builds a `CpuLoadGauge` in a field initializer. `CpuLoadGauge` in turn touches OSHI native code in its own field initializer, so constructing the periodical forces OSHI/JNA to unpack and `dlopen()` its native library at boot. On a `noexec` mount the kernel refuses to map the library and startup dies.

The fix:
- `CpuLoadGauge` no longer touches native code at construction. It seeds its baseline lazily on the first `update()` and computes load from the second run onward.
- Native access is guarded with `try/catch`. Catching `LinkageError` rather than `Throwable` keeps JVM-fatal errors such as `OutOfMemoryError` propagating. On failure it disables the metric and logs a single warning naming the likely `noexec` cause and the `jna.tmpdir` remedy.

`OshiService` is intentionally left unchanged. Its construction is already wrapped in a `catch` in `SystemStatsModule`, which falls back to the JMX probes if the native library cannot load, so it is not on this boot-failure path. `CpuLoadGauge` was the only eager OSHI consumer without such a guard.

## How Tested

Automation: `CpuLoadGaugeTest` updated
Manual test instructions: on a host with the data dir on a `noexec` mount (or by pointing `-Djna.tmpdir` at a `noexec` directory), 7.1 fails to boot before this change; with the change the server starts, logs the single CPU-load warning, and the `org.graylog2.system.cpu.percent` metric is absent rather than crashing the node.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (non-breaking change)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have requested a documentation update.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/periodical/CpuLoadGauge.java [hunk 1]
```diff
@@ -17,28 +17,56 @@
...
+            final CentralProcessor processor = processor();
+            final long[] newTicks = processor.getSystemCpuLoadTicks();
+            if (lastTicks == null) {
+                // First run: there is no previous sample to compare against yet, so just seed the baseline.
+                lastTicks = newTicks;
+                return;
+            }
+            cpuLoad = processor.getSystemCpuLoadBetweenTicks(lastTicks, newTicks) * 100.0d;
+            lastTicks = newTicks;
+        } catch (LinkageError e) {
```
Comment (kodjo-anipah) [inline graylog2-server/src/main/java/org/graylog2/periodical/CpuLoadGauge.java]: AI suggests that OSHI could throw a RuntimeException  in some cases so to be safe we should also catch that

File: graylog2-server/src/main/java/org/graylog2/periodical/CpuLoadGauge.java [hunk 2]
```diff
@@ -17,28 +17,56 @@
...
 import oshi.SystemInfo;
 import oshi.hardware.CentralProcessor;
 
 public class CpuLoadGauge implements Gauge<Double> {
 
-    private long[] lastTicks = processor().getSystemCpuLoadTicks();
+    private static final Logger LOG = LoggerFactory.getLogger(CpuLoadGauge.class);
+
+    private long[] lastTicks;
     private Double cpuLoad;
```
Comment (kodjo-anipah) [inline graylog2-server/src/main/java/org/graylog2/periodical/CpuLoadGauge.java]:
```suggestion
    private volatile Double cpuLoad;
```

**Review by kodjo-anipah — CHANGES_REQUESTED** [review]
Small comments otherwise its working, thanks!

File: graylog2-server/src/main/java/org/graylog2/periodical/CpuLoadGauge.java (hunk 1 above)
Comment (patrickmann) [reply graylog2-server/src/main/java/org/graylog2/periodical/CpuLoadGauge.java]: fixed

File: graylog2-server/src/main/java/org/graylog2/periodical/CpuLoadGauge.java (hunk 2 above)
Comment (patrickmann) [reply graylog2-server/src/main/java/org/graylog2/periodical/CpuLoadGauge.java]: fixed

**Review by kodjo-anipah — APPROVED** [review]
LGMT
