### ISSUE TITLE
Graylog does not start after upgrade from 3.3 to 4.0.1

### ISSUE THREAD

**Issue by hulkk** [Graylog2/graylog2-server#9752]
## Expected Behavior

Service should start or have better exception handling.

## Current Behavior

After upgrading Graylog 3.3.9 to 4.0.1 using yum the service does not start. Graylog's own server.log contains only info events. Following information is from /var/log/messages

```
Dec 10 11:16:14 redacted graylog-server: Exception in thread "main" java.lang.NoClassDefFoundError: org/graylog/plugins/views/search/elasticsearch/ESQueryDecorator
Dec 10 11:16:14 redacted graylog-server: at java.lang.ClassLoader.defineClass1(Native Method)
Dec 10 11:16:14 redacted graylog-server: at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
Dec 10 11:16:14 redacted graylog-server: at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
Dec 10 11:16:14 redacted graylog-server: at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
Dec 10 11:16:14 redacted graylog-server: at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
Dec 10 11:16:14 redacted graylog-server: at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
Dec 10 11:16:14 redacted graylog-server: at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
Dec 10 11:16:14 redacted graylog-server: at java.security.AccessController.doPrivileged(Native Method)
Dec 10 11:16:14 redacted graylog-server: at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
Dec 10 11:16:14 redacted graylog-server: at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
Dec 10 11:16:14 redacted graylog-server: at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:817)
Dec 10 11:16:14 redacted graylog-server: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
Dec 10 11:16:14 redacted graylog-server: at org.graylog.plugins.enterprise.ParameterSubstitutionModule.configure(ParameterSubstitutionModule.java:22)
Dec 10 11:16:14 redacted graylog-server: at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
Dec 10 11:16:14 redacted graylog-server: at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
Dec 10 11:16:14 redacted graylog-server: at org.graylog2.shared.bindings.PluginBindings.configure(PluginBindings.java:51)
Dec 10 11:16:14 redacted graylog-server: at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
Dec 10 11:16:14 redacted graylog-server: at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
Dec 10 11:16:14 redacted graylog-server: at com.google.inject.spi.Elements.getElements(Elements.java:103)
Dec 10 11:16:14 redacted graylog-server: at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
Dec 10 11:16:14 redacted graylog-server: at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
Dec 10 11:16:14 redacted graylog-server: at com.google.inject.Guice.createInjector(Guice.java:87)
Dec 10 11:16:14 redacted graylog-server: at org.graylog2.shared.bindings.GuiceInjectorHolder.createInjector(GuiceInjectorHolder.java:34)
Dec 10 11:16:14 redacted graylog-server: at org.graylog2.bootstrap.CmdLineTool.setupInjector(CmdLineTool.java:381)
Dec 10 11:16:14 redacted graylog-server: at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:196)
Dec 10 11:16:14 redacted graylog-server: at org.graylog2.bootstrap.Main.main(Main.java:50)
Dec 10 11:16:14 redacted graylog-server: Caused by: java.lang.ClassNotFoundException: org.graylog.plugins.views.search.elasticsearch.ESQueryDecorator
Dec 10 11:16:14 redacted graylog-server: at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
Dec 10 11:16:14 redacted graylog-server: at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
Dec 10 11:16:14 redacted graylog-server: at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:817)
Dec 10 11:16:14 redacted graylog-server: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
Dec 10 11:16:14 redacted graylog-server: ... 26 more
Dec 10 11:16:14 redacted systemd: graylog-server.service: main process exited, code=exited, status=1/FAILURE
Dec 10 11:16:14 redacted systemd: Unit graylog-server.service entered failed state.
```

## Your Environment

* Graylog Version: 4.0.1
* Java Version: openjdk version "1.8.0_272"
* Elasticsearch Version: 6.8.13
* Operating System: RHEL 7.9

**Comment by dennisoelkers** [comment]
Hey @hulkk,

thanks for reporting this. Do you have any plugins in your plugin folder?

**Comment by hulkk** [comment]
Thanks for the fast response!

```
-rw-r--r--. 1 root root    26678 28.1.2019 graylog-output-syslog-2.4.5.jar
-rw-r--r--. 1 root root 20239730 25.11. 20:47 graylog-plugin-aws-4.0.1.jar
-rw-r--r--. 1 root root  6463269 25.11. 20:47 graylog-plugin-collector-4.0.1.jar
-rw-r--r--. 1 root root 27709960 25.11. 19:59 graylog-plugin-enterprise-3.3.9.jar
-rw-r--r--. 1 root root 23071106 25.11. 19:59 graylog-plugin-enterprise-integrations-3.3.9.jar
-rw-r--r--. 1 root root 31860745 25.11. 19:59 graylog-plugin-integrations-3.3.9.jar
-rw-r--r--. 1 root root   302637 29.11.2019 graylog-plugin-slack-notification-1.0.5.jar
-rw-r--r--. 1 root root  7999532 25.11. 20:47 graylog-plugin-threatintel-4.0.1.jar
-rw-r--r--. 1 root root 23275853 25.11. 20:47 graylog-storage-elasticsearch6-4.0.1.jar
-rw-r--r--. 1 root root 29840631 25.11. 20:47 graylog-storage-elasticsearch7-4.0.1.jar
-rw-r--r--. 1 root root       48 25.11. 19:59 LICENSE-ENTERPRISE
-rw-r--r--. 1 root root  3077913 25.11.2019 metrics-reporter-influxdb-3.0.0.jar

```

**Comment by dennisoelkers** [comment]
3.x plugins are not compatible with 4.x. In this case it is the enterprise plugin v3.3.9 which is causing the issues. Removing it and replacing it with the v4.0.1 will fix the issue.

**Comment by hulkk** [comment]
Thanks! Now the service started.

Could it be possible that Graylog would check the plugin compatibility in startup and ignore incompatible plugins or fail gracefully and write the incompatible plugin to the log?

**Comment by dennisoelkers** [comment]
Great to hear!

Yes, that would be a good idea. We could do that at least for stock plugins (the ones we ship and/or distribute). It is probably not possible for 3rd party plugins.

**Comment by dennisoelkers** [comment]
I created an issue for this: #9753.

This issue can be closed, I guess?

**Comment by hulkk** [comment]
Yes, thanks!
