### PR TITLE
Address severe issues with AlarmCallbacks

### LINKED ISSUE #1221: AlarmCallbacks are no longer compatible with v1.1(.1)
Users noticed that for example the Slack plugin is no longer working with v1.1(.1):

    java.lang.NoSuchMethodError: org.graylog2.plugin.alarms.AlertCondition.getSearchHits()Ljava/util/List;
	at org.graylog2.alarmcallbacks.slack.SlackClient.buildPostParametersFromAlertCondition(SlackClient.java:163)
	at org.graylog2.alarmcallbacks.slack.SlackClient.trigger(SlackClient.java:107)
	at org.graylog2.alarmcallbacks.slack.SlackAlarmCallback.call(SlackAlarmCallback.java:58)
	at org.graylog2.rest.resources.streams.alerts.StreamAlertReceiverResource.sendDummyAlert(StreamAlertReceiverResource.java:168)

Indeed that method was removed in bc83b850d16a69e237cbbb4456d2a6bc64d993b2. A commit the same day (516f5227bde6227a5a79696c092f358ee9fd22f4) tried to "sustain plugin api backwards compatibility" but did not add the method back to the interface.

#### We will need to upload new alarm callback plugins that use the 1.1.2 plugin-interfaces after fixing this.

### PR DESCRIPTION
**Pull request by lennartkoopmann**
This PR fixes #1221 and #1222. Please review and merge.

I thoroughly tested with all alert condition types triggering the Slack alarm callback plugin and the PagerDuty alarm callback plugin.

(this is a replacement for #1223 which was accidentally issued against `master`)

### CODE REVIEW

File: graylog2-server/src/main/java/org/graylog2/alerts/types/DummyAlertCondition.java [hunk 1]
```diff
@@ -42,4 +44,10 @@ public String getDescription() {
     public CheckResult runCheck() {
         return new CheckResult(true, this, this.description, Tools.iso8601(), null);
     }
+
+    @Override
+    public List<Message> getSearchHits() {
+        return null;
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/alerts/types/DummyAlertCondition.java]: This should return `Collections#emptyList()` instead of `null` to prevent accidental NullPointerExceptions in the caller.

File: graylog2-server/src/main/java/org/graylog2/alerts/types/FieldContentValueAlertCondition.java [hunk 2]
```diff
@@ -124,4 +126,9 @@ protected CheckResult runCheck() {
     public String getDescription() {
         return "field: " + field + ", value: " + value;
     }
+
+    @Override
+    public List<Message> getSearchHits() {
+        return searchHits;
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/alerts/types/FieldContentValueAlertCondition.java]: I'm not sure if this class is ever used concurrently from multiple threads, but if it was, this should either return a copy of the list (`ImmutableList#copyOf()`) or change the `searchHits` field to a `CopyOnWriteArrayList`.

File: graylog2-server/src/main/java/org/graylog2/alerts/types/FieldValueAlertCondition.java [hunk 3]
```diff
@@ -175,4 +178,9 @@ protected CheckResult runCheck() {
             return new NegativeCheckResult(this);
         }
     }
+
+    @Override
+    public List<Message> getSearchHits() {
+        return searchHits;
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/alerts/types/FieldValueAlertCondition.java]: I'm not sure if this class is ever used concurrently from multiple threads, but if it was, this should either return a copy of the list (`ImmutableList#copyOf()`) or change the `searchHits` field to a `CopyOnWriteArrayList`.

File: graylog2-server/src/main/java/org/graylog2/alerts/types/MessageCountAlertCondition.java [hunk 4]
```diff
@@ -124,4 +124,10 @@ protected CheckResult runCheck() {
             return null;
         }
     }
+
+    @Override
+    public List<Message> getSearchHits() {
+        return this.searchHits;
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/alerts/types/MessageCountAlertCondition.java]: See above…

File: graylog2-server/src/main/java/org/graylog2/alerts/AbstractAlertCondition.java [hunk 5]
```diff
@@ -19,6 +19,7 @@
 import com.fasterxml.jackson.annotation.JsonIgnore;
 import com.google.common.collect.ImmutableMap;
 import com.google.common.collect.Lists;
+import org.graylog2.plugin.Message;
```
Comment (joschi) [inline graylog2-server/src/main/java/org/graylog2/alerts/AbstractAlertCondition.java]: Unused import.

File: graylog2-server/src/main/java/org/graylog2/alerts/types/DummyAlertCondition.java (hunk 1 above)
Comment (lennartkoopmann) [inline graylog2-server/src/main/java/org/graylog2/alerts/types/DummyAlertCondition.java]: Indeed. Thanks!

File: graylog2-server/src/main/java/org/graylog2/alerts/types/FieldContentValueAlertCondition.java (hunk 2 above)
Comment (lennartkoopmann) [inline graylog2-server/src/main/java/org/graylog2/alerts/types/FieldContentValueAlertCondition.java]: Agreed! We should make it a copy just to guarantee that other callbacks receive a list that has not been modified.

File: graylog2-server/src/main/java/org/graylog2/alerts/types/FieldValueAlertCondition.java (hunk 3 above)
Comment (lennartkoopmann) [inline graylog2-server/src/main/java/org/graylog2/alerts/types/FieldValueAlertCondition.java]: See above.

File: graylog2-server/src/main/java/org/graylog2/alerts/types/MessageCountAlertCondition.java (hunk 4 above)
Comment (lennartkoopmann) [inline graylog2-server/src/main/java/org/graylog2/alerts/types/MessageCountAlertCondition.java]: See above.

File: graylog2-server/src/main/java/org/graylog2/alerts/AbstractAlertCondition.java (hunk 5 above)
Comment (lennartkoopmann) [inline graylog2-server/src/main/java/org/graylog2/alerts/AbstractAlertCondition.java]: thx

**Comment by lennartkoopmann** [comment]
Thanks Jochen! :) Addressed your remarks in 17110a9.

**Comment by lennartkoopmann** [comment]
I made `getSearchHits()` return an empty `ArrayList` instead of an empty `ImmutableList` because that was the behavior before the changes and I cannot guarantee that no plugin out there is not trying to directly work on that list.

**Comment by lennartkoopmann** [comment]
Thank you! :)
